version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://user:password@db:5432/timeseller
      JWT_SECRET: your_jwt_secret
      EMAIL_HOST: smtp.example.com
      EMAIL_USER: your_email@example.com
      EMAIL_PASS: your_email_password
      KAKAO_LINK: https://open.kakao.com/o/xxxxxxx
    ports:
      - '4000:4000'
    depends_on:
      - db
  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    ports:
      - '3000:3000'
    depends_on:
      - backend
volumes:
  db_data: 